### ISSUE TITLE
Add MBoC group

### ISSUE THREAD

**Issue by BlueReZZ** [sciety/sciety#1581]
RSS feed:
- https://www.molbiolcell.org/action/showFeed?ui=2wf&mi=3tv4jw&type=search&feed=rss&query=%2526ContentItemType%253Darticle-commentary%2526target%253Ddefault

Method to request a single evaluation from the feed:
- Convention: https://www.molbiolcell.org/action/showFeed?type=search&feed=rss&query=%2526field1%253DAllField%2526text1%253D[highlight_DOI] 
- Example: https://www.molbiolcell.org/action/showFeed?type=search&feed=rss&query=%2526field1%253DAllField%2526text1%253D10.1091/mbc.P22-02-1005

A human-readable list of their evaluations
-  https://www.molbiolcell.org/action/doSearch?AllField=preprint+highlight&ContentItemType=article-commentary

**Comment by themarkness** [comment]
Tidying up stale open issues. @ShaneAlsop can we note this ticket wherever we are prioritising adding groups?

**Comment by ShaneAlsop** [comment]
> Tidying up stale open issues. @ShaneAlsop can we note this ticket wherever we are prioritising adding groups?

Hi @themarkness - Thanks for this. Please could you clarify what this means in practical terms? I'm not sure I have the full context here (and can see no previous email threads with Group representative mike Lacy), but can see that MBoC are listed as a potential Group in the [Groups document](https://docs.google.com/spreadsheets/d/1YZwlfyWsvPZSorheq57vPDGQpvLQpg9JCsDq3uTPBvI/edit#gid=0). Is this ticket now stale because we are no longer proceeding with the Group's addition? If so, is this a reminder to close tickets for Groups who don't finalise their migration to Sciety? Cheers!
