### ISSUE TITLE
Mitigate `DatasourceError grafanacloud-logs A Hypothes.is rate limiting` false positives

### ISSUE THREAD

**Issue by davidcmoulton** [sciety/sciety#2232]
The 'Edit rule' Grafana UI for this alert is https://sciety.grafana.net/alerting/H542stS4k/edit?returnTo=%2Falerting%2Fgrafana%2FH542stS4k%2Fview

Step 3: `Alert evaluation behavior` has a field `Alert state if execution error or timeout` that is currently set to `Error`. The other options for this field are `Alerting` and `OK`. 

The current `for` field value of `5 min` indicates that the alert will be pending for 5 minutes before sending switching to the `Alerting` state and sending an email

**Comment by giorgiosironi** [comment]
Looking at the false positive emails only, they are usually recovered from within 5 minutes. Probably this is even faster, and we don't receive emails due to default notification policy being configured not to send emails more frequently than 5 minutes.

Hypothesis to test: if we change the configured threshold duration (`for` label) to extend it to 15 minutes, the alert instance state might be able to recover from `Error` before the state of the alert goes from `Pending` to `Alerting`; and we wouldn't receive an email.

Changed on 2023-04-20 11:09.

**Comment by davidcmoulton** [comment]
Some documentation of alert rules & instances at https://grafana.com/docs/grafana-cloud/alerting/fundamentals/state-and-health/

**Comment by giorgiosironi** [comment]
Received email:
`[FIRING:1] Sciety (DatasourceError grafanacloud-logs A Hypothes.is rate limiting) alert`
at 4:35 PM. Resolved email at 4:40 PM, so first attempt at mitigation didn't succeed.

**Comment by giorgiosironi** [comment]
The email has these labels:
```
alertname | DatasourceError
datasource_uid | grafanacloud-logs
grafana_folder | Sciety
ref_id | A
rulename | Hypothes.is rate limiting
```
so https://community.grafana.com/t/alerting-notification-policy-datasourceerror-datasourcenodata/59638 may be right in suggesting that a filter on the notification policy of `alertname != DatasourceError` might be ok to silence these or to then route them to another channel.

**Comment by davidcmoulton** [comment]
Attempting to remove notifications when there is an execution error, we changed the value of:
```
3. Alert evaluation behavior > Configure no data and error handling > Alert state if execution error or timeout
```
from `Error` to `OK` in the drop down.
