### ISSUE TITLE
Run make update-datastudio automatically

### ISSUE THREAD

**Issue by giorgiosironi** [sciety/sciety#2860]

**Comment by giorgiosironi** [comment]
I found an AWS IAM machine-oriented user with the right permissions to put an events database dump into our S3 bucket:
https://us-east-1.console.aws.amazon.com/iam/home?region=us-east-1#/users/details/ScietyEventsShipper?section=permissions
Credentials just used 12 hours ago!

**Comment by giorgiosironi** [comment]
`docker run -ti google/cloud-sdk:slim gcloud version` look promising for the BigQuery part, and it's easy to `apt install jq`.

**Comment by giorgiosironi** [comment]
The only sane way to run multiple containers sequentially is through [`initContainers`](https://github.com/kubernetes/kubernetes/issues/45759), where the last container can be in the `containers` section.

**Comment by de-code** [comment]
Responding here to your question on Slack.

Probably the preferred way would be for Data Hub to pull the data as that would allow for better monitoring.

In Data Hub, we do have a configurable pipeline to import CSV files on an S3 bucket and import them into BigQuery.
(We of course would also need to configure the credentials to get access to the S3 bucket)

If instead of a JSONL file you could generate a CSV file, then we could use the existing pipeline.

We don't currently have a pipeline for JSONL (or JSON) files. But as an alternative we could create that too.
(Internally the CSV pipeline is also generating a JSONL file so it would build on many things already there)

Another alternative would be for Sciety to offer an API, it could just be the same raw data. It could be access controlled.
We have a "generic" Web API pipeline that can be configured for that.
That way we can configure the full polling schedule in Data Hub.
(As opposed to files being generated at a different schedule than when we poll them from the bucket)

**Comment by de-code** [comment]
If it is helpful, I could give a very quick tour of how we configure the Data Hub CSV and Web API pipeline and what options they have?

**Comment by giorgiosironi** [comment]
Next thing to try then: generate a CSV and see what is in there; that would appear in `s3://sciety-data-extractions`.

**Comment by giorgiosironi** [comment]
Now available at `s3://sciety-data-extractions/events-from-cronjob.csv`.

**Comment by giorgiosironi** [comment]
Monitor with `kubectl get cronjobs` and `kubectl logs`.

**Comment by giorgiosironi** [comment]
The IAM user to give access to from another account might be `arn:aws:iam::512686554592:user/data-pipeline`.

**Comment by giorgiosironi** [comment]
[The bucket and its permissions](https://s3.console.aws.amazon.com/s3/buckets/sciety-data-extractions?region=us-east-1&tab=permissions) are not managed in Terraform currently.

**Comment by giorgiosironi** [comment]
Following https://docs.aws.amazon.com/AmazonS3/latest/userguide/example-walkthroughs-managing-access-example2.html, gave `GetObject` access to the contents of this bucket to the account 512686554592 `root` user which can then delegate it.

**Comment by giorgiosironi** [comment]
Tested this is what I get as an admin on 512686554592:
```
$ aws s3 cp s3://sciety-data-extractions/events-from-cronjob.csv ./events-from-cronjob.csv
download: s3://sciety-data-extractions/events-from-cronjob.csv to ./events-from-cronjob.csv
$ aws s3 ls s3://sciety-data-extractions/

An error occurred (AccessDenied) when calling the ListObjectsV2 operation: Access Denied
```

**Comment by giorgiosironi** [comment]
Might mean attaching a new policy to the ones I see in `aws iam list-attached-group-policies --group-name data-pipeline` that gives the same access to `s3://sciety-data-extractions`. @de-code can you confirm?

**Comment by giorgiosironi** [comment]
Closing the ticket as part of its week-long timebox, will report at Tuesday gold cards.

**Comment by de-code** [comment]
Can we add a CSV header row with field names?

I also noticed that the payload is kept as JSON. This might create some challenges. I will look a bit more into it.

**Comment by de-code** [comment]
Should hopefully be a small change to add the header row: https://stackoverflow.com/a/65346207/8676953
