### ISSUE TITLE
Display eLife reviews for medrxiv articles

### ISSUE THREAD

**Issue by hdrury1** [sciety/sciety#388]
Example of medRxiv article with reviews from eLife:

https://www.medrxiv.org/content/10.1101/2020.09.03.20184051v2.full

These reviews should be displayed in the activity feed in the same way we currently display reviews of bioRxiv articles. 'Read original source' should link back to the Hypothes.is comments on medRxiv page.

- ~add community avatar~
- ~add review content~
- ~add link to original source~
- [x] update scripts to include medRxiv reviews

### Refactoring
- [x] run biorxiv & medrxiv requests in parallel

### Tech debt hour

- [x] check avatars from Twitter in Firefox
- [x] bioRxiv URLs aren't consistent, but code requires a specific form (`curl -v "https://api.hypothes.is/api/search?uri.parts=biorxiv&limit=100" |  jq --raw-output ".rows[].target[].source"`)

**Comment by giorgiosironi** [comment]
Able to reproduce the biorxiv and medrxiv avatar breaking on Firefox 84 with [Enhanced Tracking Protection](https://support.mozilla.org/en-US/kb/enhanced-tracking-protection-firefox-desktop) setting it to `Strict` rather than `Standard`. More spikes needed to understand what/whether to do something.
