### ISSUE TITLE
Initial ideas for BioRxiv evaluation panel

### ISSUE THREAD

**Issue by NickDuf** [sciety/sciety#587]
## Description
Redesign BioRxiv evaluation panel. Work to include
- Improved visual design for panels and bracelet
- Organise information hierarchy
- Links back to evaluation sources
- Powered by Sciety link

**Comment by NickDuf** [comment]
@BlueReZZ do you have any screen shots for the Trip tab with info inside of it?

**Comment by BlueReZZ** [comment]
> @BlueReZZ do you have any screen shots for the Trip tab with info inside of it?

We do not. I checked the examples we have access to and they mainly focus on community review. However, we have good examples of TRiP content on Sciety from Review Commons and eLife:

RC: https://sciety.org/articles/activity/10.1101/2020.02.25.963017
eLife: https://sciety.org/articles/activity/10.1101/2020.06.14.150946

All other content from both groups is TRiP content too should you need other examples.

Worth noting that eLife can provide context for these activity items via tags so that we can tell if they are an Evaluation Summary, a Peer Review or an Author Response but Review Commons do not. A design that does not distinguish between the types is likely most suitable.
