### ISSUE TITLE
Address delay between posting of article to biorxiv and ingestion in crossref

### ISSUE THREAD

**Issue by giorgiosironi** [sciety/sciety#664]
- [x] Remove 10.1101/2021.04.21.440786 temporarily from events
- [x] Reach out to editorial team
- [x] Contact CrossRef about the delay. The Editorial team can delay posting reviews if necessary.

**Comment by hdrury1** [comment]
Response from the eLife Editorial team:

> Hi Hannah, if authors don’t post a preprint at full submission, we still prepare public reviews, such that we hope to persuade the authors to post a preprint with the reviews at the end of the process; it won’t happen often but it’ll happen occasionally. Hope that helps?!

**Comment by hdrury1** [comment]
Closing for now- I'm not convinced this is going to be a regular enough occurrence to affect priority of other tasks. Andy has confirmed we might expect to see this once every couple of months.

**Comment by erkannt** [comment]
10.1101/2021.04.21.440786 appears to be working now

**Comment by BlueReZZ** [comment]
This appears to have been down to an issue with CrossRef data being out of date around that time. After discussing with bioRxiv and PubPub who saw similar issues that are now resolved it seems the infrastructure at CrossRef was causing this rather than any incorrect or problematic process at eLife, Sciety or bioRxiv.

Incident report for reference: https://status.crossref.org/incidents/fpl9nwc77src
